# Generated by Django 2.0.3 on 2018-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180331_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleorg',
            name='article_nums',
            field=models.IntegerField(default=0, verbose_name='文章数'),
        ),
        migrations.AddField(
            model_name='articleorg',
            name='readers',
            field=models.IntegerField(default=0, verbose_name='阅读人数'),
        ),
    ]
