# Generated by Django 2.0.3 on 2018-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180331_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='', upload_to='authors/%Y%m', verbose_name='头像'),
        ),
    ]
