# Generated by Django 2.0.3 on 2018-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
