# Generated by Django 2.0.3 on 2018-04-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbrowsedarticles',
            options={'verbose_name': '用户文章', 'verbose_name_plural': '用户文章'},
        ),
    ]
