# Generated by Django 2.0.3 on 2018-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180402_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='article_name',
            field=models.CharField(max_length=50, verbose_name='文章关键词'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
