# Generated by Django 2.0.3 on 2018-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180405_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='image/%Y/%m'),
        ),
    ]
