# Generated by Django 2.0.3 on 2018-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_len',
            field=models.CharField(choices=[('dp', '短篇'), ('zp', '中篇'), ('cp', '长篇')], max_length=2, verbose_name='文章长度'),
        ),
    ]
