# Generated by Django 2.0.3 on 2018-04-01 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180331_1850'),
        ('articles', '0003_auto_20180330_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.ArticleOrg', verbose_name='组织机构'),
        ),
    ]
