# Generated by Django 2.0.3 on 2018-04-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180403_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='art_content',
        ),
    ]
