# Generated by Django 2.0.3 on 2018-04-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_author_image'),
        ('articles', '0008_auto_20180403_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Author', verbose_name='作者'),
        ),
    ]
