# Generated by Django 2.0.3 on 2018-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='articles/%Y%m', verbose_name='封面图'),
        ),
    ]
